### ISSUE TITLE
NMEA NAME should be used to uniquely identify sensors

### ISSUE THREAD

**Issue by schrockwell** [opensailing/nautic_net_device#2]
Currently we are using a 32-bit combination of "manufacturer code" and "unique number". This is insufficient. We should be using the entire 64-bit value of the NMEA NAME, which is available from the network.

The identifier is defined by `NauticNet.DeviceInfo.identifier/1` and `hw_id/1` which should probably both return the 64-bit number. No need for the intermediate tuple.

**Comment by CaptChrisD** [comment]
Done with `Discovery` now calling into `nmea` lib for devices on the network info.
