### ISSUE TITLE
Replace socketcand with more robust solution

### ISSUE THREAD

**Issue by schrockwell** [opensailing/nautic_net_device#3]
Per @CaptChrisD, the current implementation of `NauticNet.CAN.PiCAN.Server`, which leverages `socketcand`, is insufficient to handle the bandwidth of a NMEA2K network with high utilization (e.g. 90%+).

I missed the details on the specific solution he had in mind, but it was a fork of some Erlang NIF.

**Comment by CaptChrisD** [comment]
Done inside of `nmea` lib.
